steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git submodule init
        git submodule update
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    env:
      - "DEBIAN_FRONTEND=noninteractive"
    args:
      - '-c'
      - |
        if [ -n "${_TEST}" ]; then
          apt update && apt install -y wget &&
          wget -c https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0/graalvm-ce-java11-linux-amd64-21.0.0.tar.gz -O - | tar -xvz &&
          mv graalvm-ce-java11-21.0.0 /tmp/graalvm &&
          export PATH=/tmp/graalvm/bin:$$PATH &&
          export JAVA_HOME=/tmp/graalvm &&
          java -version &&
          ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
        fi
  - name: 'openjdk:11.0.10-jdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -n "${_TEST}" ]; then
          ./gradlew test
        fi



