steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git submodule init
        git submodule update
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    env:
      - "DEBIAN_FRONTEND=noninteractive"
    args:
      - '-c'
      - |
        if [ -n "${_TEST}" ]; then
          apt update && apt search openjdk && apt install -y openjdk-11-jdk &&
          java -version &&
          ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
        fi
  - name: 'openjdk:11.0.10-jdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -n "${_TEST}" ]; then
          ./gradlew test
        fi



