steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git submodule init
        git submodule update
  - name: openjdk:11.0.10-jdk
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -n "${_TEST}" ]; then
          ./gradlew test
        fi