timeout: 7200s
options:
  machineType: N1_HIGHCPU_32
steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git submodule init
        git submodule update
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    timeout: 7200s
    env:
      - "DEBIAN_FRONTEND=noninteractive"
    args:
      - '-c'
      - |
        if [ -n "${_NATIVE}" ]; then
          apt update && apt install -y wget &&
          wget -c https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-${_GRAAL_VM_VERSION}/graalvm-ce-java11-linux-amd64-${_GRAAL_VM_VERSION}.tar.gz -O - | tar -xz &&
          mv graalvm-ce-java11-${_GRAAL_VM_VERSION} /tmp/graalvm &&
          export PATH=/tmp/graalvm/bin:$$PATH &&
          export JAVA_HOME=/tmp/graalvm &&
          java -version &&
          gu install native-image &&
          ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true -x test
        fi
  - name: 'openjdk:11.0.10-jdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -n "${_TEST}" ]; then
          ./gradlew test
        fi



